services:
    ai:
        image: notebookum-ai:v1.0.0
        restart: unless-stopped
        deploy:
            replicas: 2
        networks:
            notebookum-network:
                aliases:
                    - ai.universidad.localhost
        environment:
            - GROQ_API_KEY=${GROQ_API_KEY:-}
            - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
            - HOST=0.0.0.0
            - PORT=5000
            - LOG_LEVEL=INFO
            - HEALTHCHECK_AI=false
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${REDIS_PASSWORD:-}
            # Consul Service Discovery
            - CONSUL_HOST=consul
            - CONSUL_PORT=8500

networks:
    notebookum-network:
        external: true