services:
  ai:
    build: .
    image: notebookum-ai:v1.0.0
    restart: unless-stopped
    deploy:
      replicas: 2
    networks:
      notebookum-network:
        aliases:
          - ai.universidad.localhost
    environment:
      - CONSUL_URL=http://consul:8500
      - CONSUL_TOKEN=${CONSUL_TOKEN:-}

networks:
  notebookum-network:
    external: true